[package]
name = "vulkan-exp"
version = "0.1.0"
authors = ["Sam Lakerveld <darkwater124@gmail.com>"]
edition = "2018"

[dependencies]
openvr          = "0.5.2"
vulkano         = "0.11.1"
vulkano-shaders = "0.11.1"
vulkano-win     = "0.11.1"
winit           = "0.18.0"
